### ISSUE TITLE
Erro variável id_orgao_acesso_externo=0

### ISSUE THREAD

**Issue by jefersongoliveira** [anatelgovbr/mod-sei-pesquisa#10]
Prezado(a), saudações!
Verifiquei que no menu principal onde o usuário externo acessa a opção de "Pesquisa Pública" está com o valor fixo id_orgao_acesso_externo=0 onde no caso do nosso sistema deveria estar dinâmico com o valor id_orgao_acesso_externo=3. As outras opções do menu "Controle de Acessos Externos", "Alterar Senha", "Peticionamento", "Recibos Eletrônicos de Protocolo" e "Intimações Eletrônicas" estão com o valor correto, ou seja, 3.

Acredito que com a busca por meio do link "https://github.com/anatelgovbr/mod-sei-pesquisa/search?q=id_orgao_acesso_externo&type=" poderá facilitar a localização desta variável fixa.

**Comment by neijobson** [comment]
@jefersongoliveira Isso ocorre QUANDO utiliza múltiplos órgãos?
No caso, o login de Acesso Externo do SEI nesse caso foi de um órgão específico em uma instalação de múltiplos órgãos?

Manda links para entendermos melhor.

**Comment by neijobson** [comment]
@jefersongoliveira 
Correção realizada nesse merge: https://github.com/anatelgovbr/mod-sei-pesquisa/pull/14/files

v4.1.1 publicada: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
