### ISSUE TITLE
Problema logo com link quebrado no SUPER.gov.br 4.0.9.13

### ISSUE THREAD

**Issue by tadeuufscar** [anatelgovbr/mod-sei-pesquisa#13]
Prezados, instalei o módulo da ANATEL de Pesquisa Pública na versão 4.1.0 no SUPER.gov.br versão 4.0.9.13 e notei um problema na exibição do logo com link quebrado, segue as imagens:

### TELA LOGO NORMAL, SUPER.GOV
![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/121962281/854a953a-4cac-416e-a54c-2713ee2050c8)

### TELA LINK QUEBRADO NO LOGO, MÓDULO PESQUISA PÚBLICA
![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/121962281/e9fc945f-4061-48da-8abb-d9d49b01a89b)

**Comment by neijobson** [comment]
@tadeuufscar Não mantemos o módulo para o SUPER.
É compatível, de forma que pode fazer este ajuste local.
Mas não mudaremos aqui no módulo no Github.
