### ISSUE TITLE
Script de instalação SEI/SIP de versão 4.1.1 não funciona com  SEI 4.0.11

### ISSUE THREAD

**Issue by ljsts01** [anatelgovbr/mod-sei-pesquisa#15]
O trecho abaixo , existente tanto nos arquivos de instalação do SEI quanto do SIP da versão 4.1.1 do módulo, não funciona com a versão 4.0.11 do SEI.

O motivo é que o valor de `VERSAO_INFRA` no SEI 4.0.11 é `2.0.6`. Dessa forma, pela lógica da validação abaixo, fica `206 < 16123` e então o script falha.

```php
//testando versao do framework
            $numVersaoInfraRequerida = '1.612.3';
            $versaoInfraFormatada = (int)str_replace('.', '', VERSAO_INFRA);
            $versaoInfraReqFormatada = (int)str_replace('.', '', $numVersaoInfraRequerida);

            if ($versaoInfraFormatada < $versaoInfraReqFormatada) {
                $this->finalizar('VERSÃO DO FRAMEWORK PHP INCOMPATÍVEL (VERSÃO ATUAL ' . VERSAO_INFRA . ', SENDO REQUERIDA VERSÃO IGUAL OU SUPERIOR A ' . $numVersaoInfraRequerida . ')', true);
            }
```

**Comment by neijobson** [comment]
@ljsts01
Problema resolvido na versão que acabamos de publicar, a v4.1.2.
Leia atentamente os notes da release e o README.

https://github.com/anatelgovbr/mod-sei-pesquisa/releases
