### ISSUE TITLE
Erro de valor nulo ao instalar versão 4.1.1 do módulo com SEI 4.0.11

### ISSUE THREAD

**Issue by ljsts01** [anatelgovbr/mod-sei-pesquisa#16]
Comentamos a validação mencionada em https://github.com/anatelgovbr/mod-sei-pesquisa/issues/15 a fim de prosseguirmos com a instalação.

O script do SIP funciona sem problemas.

Mas o script do SEI apresenta um outro erro durante a instalação:

```
00030 - INSERINDO PARAMETRO "DATA_CORTE" NA TABELA md_pesq_parametro

Descrição:

[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'valor', table 'Sei4.dbo.md_pesq_parametro'; column does not allow nulls. INSERT fails.
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.
```

Mais detalhes no arquivo em anexo.

**Comment by neijobson** [comment]
@ljsts01 
Antes de tudo, informo que publicamos a v4.1.2, que é compatível com o SEI 4.0.11. https://github.com/anatelgovbr/mod-sei-pesquisa/releases
Leia atentamente os notes da release e o README.

Sobre o problema indicado acima nessa Issue #16, pode ter ocorrido algum problema local nessa instalação.
Ocorre que a tabela "md_pesq_parametro" foi criada pelo script do SEI do módulo na instalarv300, primeira versão que passou a ter tabela de parametrizações para o menu de Administração correspondente.

1. Veja na linha 146 do script do SEI que a tabela é criada com apenas duas colunas e desde sempre a coluna "valor" foi criada para aceitar NULL: https://github.com/anatelgovbr/mod-sei-pesquisa/blob/871fa24b494ea4aafbf45c81c57dff121952a7a7/sei/scripts/sei_atualizar_versao_modulo_pesquisa.php#L146C13-L146C13
2. Conferi em versões antigas do módulo e no script a coluna "valor" sempre foi sinalizada para aceitar NULL.
3. Dessa forma, altere manualmente antes no banco de dados tal coluna para que aceite NULL.

Realizei teste agora fazendo instalação do zero em banco SQL Server e o script funcionou como esperado. Prints abaixo:

- A execução do script do SEI no SQL Server funcionou até o final:
![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/49068090/2cb2765c-18e9-40ed-b790-e1aee87bb6f9)

- Criou a tabela com a coluna "valor" aceitando NULL:
![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/49068090/346452e9-874b-49ea-93e8-3e6ce27e474e)

- Com o insert do parâmetro DATA_CORTE normal, com valor NULL na coluna "valor":
![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/49068090/f29ce2c5-38d8-4817-8c9e-bb9d0806335c)
