### ISSUE TITLE
Falha de segurança na validação do captcha

### ISSUE THREAD

**Issue by pablodurans-trt16** [anatelgovbr/mod-sei-pesquisa#17]
A validação do Captcha está baseada na comparação de 2 valores que vem do usuário, este são:

- $_POST['txtInfraCaptcha']
- $_POST['hdnCaptchaSha1']

Uma forma simples de burlar via ferramenta de requisições http (como curl ou postman) é fixar estes valores de forma a satisfazer a comparação sha1(mb_strtoupper($_POST['txtInfraCaptcha'])) != $_POST['hdnCaptchaSha1']) (presente na lina 124 do arquivo md_pesq_controlador_ajax_externo.php)

**Comment by neijobson** [comment]
@pablodurans-trt16 
Como você sugere uma melhoria na última versão, que está na master agora, para não termos esse problema?

**Comment by neijobson** [comment]
@pablodurans-trt16
O problema indicado foi corrigido na v4.1.2: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
Caso já tenha instalado, baixe os códigos novamente e sobrescreva.
