### ISSUE TITLE
Erro no carregamento de processos com muitos volumes

### ISSUE THREAD

**Issue by carlacastilhos** [anatelgovbr/mod-sei-pesquisa#21]
Estamos com projeto de digitalização na ANM em curso e temos processos ativos desde 1936, que geram uma quantidade muito excessiva de volumes no SEI.

Na pesquisa interna, conseguimos visualizar os documentos, ainda que com dificuldade de carregamento.

Entretanto, na pesquisa pública ocorre erro e o processo não é carregado, conforme demonstrado no vídeo:

[https://www.loom.com/share/dad0bc46bace4657ae54526cc9b008b1?sid=c33531ee-0232-4e4d-a62f-6ff6d0a9e41f](url)

Solicito apoio nesta demanda para possibilitarmos a consulta do processo aos usuários externos.

**Comment by neijobson** [comment]
@carlacastilhos 
Não limitação do módulo de Pesquisa Pública.
Tente acessar pelo Acesso Externo do SEI sobre um processo nessa situação que vai dar o mesmo problema.

Para ampliar limites do SEI para lidar com casos assim, precisam ajustar a opção pertinente na chave "Limites" dentro do arquivo de ambiente ConfiguracaoSEI.php.

Contudo, alerto que não é recomendado fazerem digitalização de processos físicos documento a documento e inserir no SEI. A recomendação para digitalização e posterior carregamento no SEI seria um PDF por Volume do processo.
