### ISSUE TITLE
A variável id_orgao_acesso_externo está fixo com o valor 0

### ISSUE THREAD

**Issue by jefersongoliveira** [anatelgovbr/mod-sei-pesquisa#22]
Por meio do link https://[URL_DO_SISTEMA]/sei/modulos/pesquisa/md_pesq_processo_pesquisar.php?acao_externa=protocolo_pesquisar&acao_origem_externa=protocolo_pesquisar&id_orgao_acesso_externo=3 é informado o valor dinâmico da variável id_orgao_acesso_externo igual a 3.
Após a geração de busca e retorno dos resultados,  o sistema não considera este valor, passando o valor 0 para a geração do link dinâmico https://[URL_DO_SISTEMA]/sei/modulos/pesquisa/md_pesq_processo_exibir.php?2fCdJjdrvF0D4zg7XsWRLLi6wqe7VxK7s_x3N70OQ-_ZG4vIBmoYPRPC0CtWw78OMj9m32QEKle3_WUz2BrUu6nUcs9xz5Fgtc1KuCAhpNMJnYJ000PQeFFmeNxVsqEa. Ocasionando erro na linha 177 do arquivo MdPesqPesquisaUtil.php

Verifiquei que o valor id_orgao_acesso_externo está fixo como '0' em várias partes do sistema podendo ocasionar erros ainda desconhecidos.

**Comment by neijobson** [comment]
@jefersongoliveira

O problema indicado foi corrigido na v4.1.1: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
Caso já tenha instalado, baixe os códigos novamente e sobrescreva.

**Comment by jefersongoliveira** [comment]
Prezado @neijobson, informo que o erro ainda persiste. Basta procurar por id_orgao_acesso_externo=0 no projeto, irá verificar 9 correspondências nos arquivos ..modulos/pesquisa/md_pesq_processo_exibir.php,  ..modulos/pesquisa/md_pesq_processo_pesquisar.php e  ..modulos/pesquisa/MDPesqBuscaProtocoloExterno.php,

**Comment by neijobson** [comment]
Caro @jefersongoliveira 
Corrigimos o que foi reportado sobre a montagem do link a partir do menu no Acesso Externo.

Sobre os demais pontos, não apresentou erro na pesquisa a partir de id_orgao_acesso_externo=0
Pode testar e nos reportar problemas depois do teste?

**Comment by neijobson** [comment]
@jefersongoliveira 
Republiquei agora a v4.1.2 do módulo com correções e melhorias: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
Leia os releases novamente para ver mais detalhes!

Além do funcionamento fim a fim do id_orgao_acesso_externo dos vários IDs, adicionamos campo novo na tela de Pesquisa Pública "Órgão Gerador".

Também teve uma correção na validação do CAPTCHA no Gerar PDF do processo.
