### ISSUE TITLE
Erro exibição logo SEI barra topo

### ISSUE THREAD

**Issue by tadeuufscar** [anatelgovbr/mod-sei-pesquisa#25]
A página `http://localhost/sei/modulos/pesquisa/md_pesq_processo_pesquisar.php?acao_externa=protocolo_pesquisar&acao_origem_externa=protocolo_pesquisar&id_orgao_acesso_externo=0` exibe o link quebrado no logo do SEI.

O endereço que tenta localizar é `http://localhost/sei/modulos/pesquisa/svg/sei_barra-azul.svg`, porém o módulo só posui o `svg/sei_barra.svg`

* Versão SEI 4.0.12.15
* Versão módulo pesquisa 4.1.2

![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/121962281/fc21a11e-0f5f-4890-b263-6bb9bc20b258)

**Comment by neijobson** [comment]
@tadeuufscar 
Não damos suporte ao módulo no SUPER. Utilize o SEI 4.0.12.

Ainda, sugerimos que utilize o SEI Localhost: http://bit.ly/SEI_Manual_Padroes_Desenvolvimento_Modulos

**Comment by tadeuufscar** [comment]
Bom dia @neijobson , obrigado pelas dicas! A versão que estamos usando é a disponibilizada aqui https://github.com/pengovbr/sei/releases/tag/4.0.12.15

![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/121962281/656047f3-b7b7-4c31-9ef7-25fa4d56f189)

Ele não é mais o SUPER, vejo a interface igual do SEI v4, mas vejo tbm que acrescentaram o tema Gov.BR no esquema de cores, e por conta disso foi alterado o arquivo `infra/infra_php/InfraPaginaEsquema3.php` adicionando o `ESQUEMA_DSGOV`.

![image](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/121962281/264697b7-ae1b-4451-a763-82a8e759da19)

Estou comentando só pra deixar registrado caso outros tenham esse problema.

**Comment by caduvieira** [comment]
Assim como foi incorporado no módulo o sei_barra.svg eu sugiro adicionar o sei_barra-azul.svg

**Comment by tadeuufscar** [comment]
Bom dia, fiz o teste da alteração e deu certo! 

Porém notei que o logo que foi adicionado `sei_barra-azul.svg` tem um tamanho muito maior que o logo `sei_barra.svg`, aparentemente não deu nenhum problema no módulo, mas não seria melhor seguir o tamanho do `sei_barra.svg`? Digo isso pq relatei sobre isso aqui: https://github.com/pengovbr/sei/issues/339

**Comment by caduvieira** [comment]
Pode sim.

**Comment by neijobson** [comment]
@tadeuufscar 
Adicionei essa imagem nova no módulo de Pesquisa. Liberei uma atualização ontem.

Sobre revisar o tamanho do SVG dessa outra logo (https://github.com/pengovbr/sei/issues/339), quando o @caduvieira me enviar novo arquivo do SVG ou novo Pull Request aqui no módulo Pesquisa aí subimos. Também percebi a imagem grande em comparação do outro SVG.
