### ISSUE TITLE
Comportamento inconsistente nas pesquisas (versão 4.1.1)

### ISSUE THREAD

**Issue by ljsts01** [anatelgovbr/mod-sei-pesquisa#27]
Bom dia,

Temos o módulo SEI Pesquisa Pública 4.1.1 instalado no SEI 4.0.9, atualmente em ambiente de homologação para validação.

A paginação do módulo de consulta pública está apresentando intermitência, ora funcionando corretamente, ora trazendo apenas algumas paginas, ora não trazendo nenhuma pagina, além da primeira.

Em uma consulta de exemplo, foi marcado Pesquisar em Processos (sem documentos). O total de registros retornados deve ser 234. No print abaixo, pode-se ver ele retornou, em uma determinada pesquisa, 184, 50 a menos. E à direita o primeiro conjunto de paginação não foi aplicado, dos registros entre 50 e 100.

![Imagem1](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/107943941/bea8d8e7-5321-40a0-8ba6-9dc8fc352bb1)

Em pesquisa realizada em seguida, a paginação não foi carregada, sendo exibido apenas os 50 primeiros registros

![Imagem2](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/107943941/c7e47d38-54f6-4ff6-9f4f-ed71ae445f64)

Algumas requisições estavam dando time out:

![Imagem3](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/107943941/22e8a87a-47e3-4ad6-ba31-ec6171fda714)

Mas nessa pesquisa ele conseguiu retornar os 234, mesmo com os time-outs:

![Imagem4](https://github.com/anatelgovbr/mod-sei-pesquisa/assets/107943941/22094be4-c314-4262-bfec-764695e9e1dd)

Outro comportamento incorreto é que, após a primeira consulta com um interessado, ao escolher outro interessado ou algum outro filtro, a paginação deixa de funcionar.

Parece que as variáveis do javascript acabam ficando setadas mesmo após a primeira pesquisa.

**Comment by ljsts01** [comment]
As alterações abaixo no arquivo md_pesq_processo_pesquisar.php parecem resolver o problema, mas não temos certeza.

```diff
$('#divInfraAreaTelaD').on('scroll', function() {
            clearTimeout(timer);
            timer = setTimeout(function() {
                if(($('#divInfraAreaTelaD').prop('scrollHeight') - $('#divInfraAreaTelaD').scrollTop()) <= Math.ceil($('#divInfraAreaTelaD').height()) && paginar) {
                    $('.ajax-loading').show();
                    $.post('<?= $strLinkAjaxPesquisar ?>&isPaginacao=true&inicio='+buscaInicio+'&rowsSolr='+rowsSolr, $('#seiSearch').serialize()).done(function(data){
                        if($(data).find('resultado').length > 0){
                            $('.retorno-ajax > table > tbody:last-child').append($(data).find('resultado').html());
                            buscaInicio += rowsSolr;
                        }
                        if($(data).find('consultavazia').length > 0){
                            $('.total-registros-infinite').html('A pesquisa encontrou '+$('.retorno-ajax > table tbody tr.pesquisaTituloRegistro').length+' resultado(s).');
-                            paginar = false;
+                            //paginar = false;
                            updateCaptcha();
                        }
                    }).always(function() {
                        $('.ajax-loading').hide();
                    });
                }
            }, 500);
        });
 ```
 ```diff
 $('body').on('submit', '#seiSearch', function(e){
            e.preventDefault(); e.stopPropagation();
            $('input[name=partialfields]').val('');
            partialFields();
+            buscaInicio = 0;
 
            $('.retorno-ajax > table > tbody tr, .sem-resultado').remove();
            $('.total-registros-infinite').empty();
 
            <? if($bolCaptcha): ?>
                if (infraTrim(document.getElementById('txtInfraCaptcha').value) == '') {
                    alert('Informe o código de confirmação.');
                    document.getElementById('txtInfraCaptcha').focus();
                    return false;
                }else{
                    document.getElementById('hdnInfraCaptcha').value='1';
                }
<? endif; ?>
 
            $('.ajax-loading').show();
            $.post('<?= $strLinkAjaxPesquisar ?>&isPaginacao=true&inicio=0&rowsSolr='+rowsSolr, $('#seiSearch').serialize()).done(function(data){
                if($(data).find('resultado').length > 0){
                    $('.retorno-ajax > table > tbody:last-child').append($(data).find('resultado').html());
                    buscaInicio += rowsSolr;
                }
                if($(data).find('consultavazia').length > 0){
                    $('.retorno-ajax').append($(data).find('consultavazia').html());
                }
            }).always(function() {
                $('.ajax-loading').hide();
                updateCaptcha();
            });
        });
```

Na primeira alteração, trecho `paginar = false;` foi comentado. Com isso o sistema sempre tenta obter uma proxima página. Se ele já tiver terminado, ok, só não vai retornar mais páginas.

Na segundo foi forçada a inicialização do `buscaInicio = 0`, dessa forma sempre ao submeter o formulário, o contador de busca reinicia.

**Comment by neijobson** [comment]
@ljsts01 
Vamos verificar para tentar reproduzir e conferir os ajustes sugeridos.
Contudo, atualize o SEI para 4.0.12. A versão 4.1.0 do módulo funciona no SEI 4.0.12. Não use no SEI 4.0.9.

**Comment by dfdiasbr** [comment]
Nei, bom dia. Nós fizemos testes aqui e conseguimos corrigir. O que fizemos foi: 

1 - Comentar o _paginar = false_ em:

$('#divInfraAreaTelaD').on('scroll', function() {
            clearTimeout(timer);
            timer = setTimeout(function() {
                if(($('#divInfraAreaTelaD').prop('scrollHeight') - $('#divInfraAreaTelaD').scrollTop()) <= Math.ceil($('#divInfraAreaTelaD').height()) && paginar) {
                    $('.ajax-loading').show();
                    $.post('<?= $strLinkAjaxPesquisar ?>&isPaginacao=true&inicio='+buscaInicio+'&rowsSolr='+rowsSolr, $('#seiSearch').serialize()).done(function(data){
                        if($(data).find('resultado').length > 0){
                            $('.retorno-ajax > table > tbody:last-child').append($(data).find('resultado').html());
                            buscaInicio += rowsSolr;
                        }
                        if($(data).find('consultavazia').length > 0){
                            $('.total-registros-infinite').html('A pesquisa encontrou '+$('.retorno-ajax > table tbody tr.pesquisaTituloRegistro').length+' resultado(s).');
                            //paginar = false;
                            updateCaptcha();
                        }
                    }).always(function() {
                        $('.ajax-loading').hide();
                    });
                }
            }, 500);
        });

com isso o sistema sempre tenta obter uma próxima página. Se ele já tiver terminado, ok, só não vai retornar mais páginas.

2 - Forçamos a inicialização do _buscaInicio = 0_ em:

$('body').on('submit', '#seiSearch', function(e){
            e.preventDefault(); e.stopPropagation();
            $('input[name=partialfields]').val('');
            partialFields();
            buscaInicio = 0;
 
            $('.retorno-ajax > table > tbody tr, .sem-resultado').remove();
            $('.total-registros-infinite').empty();
 
            <? if($bolCaptcha): ?>
                if (infraTrim(document.getElementById('txtInfraCaptcha').value) == '') {
                    alert('Informe o código de confirmação.');
                    document.getElementById('txtInfraCaptcha').focus();
                    return false;
                }else{
                    document.getElementById('hdnInfraCaptcha').value='1';
                }
<? endif; ?>
 
            $('.ajax-loading').show();
            $.post('<?= $strLinkAjaxPesquisar ?>&isPaginacao=true&inicio=0&rowsSolr='+rowsSolr, $('#seiSearch').serialize()).done(function(data){
                if($(data).find('resultado').length > 0){
                    $('.retorno-ajax > table > tbody:last-child').append($(data).find('resultado').html());
                    buscaInicio += rowsSolr;
                }
                if($(data).find('consultavazia').length > 0){
                    $('.retorno-ajax').append($(data).find('consultavazia').html());
                }
            }).always(function() {
                $('.ajax-loading').hide();
                updateCaptcha();
            });
        });

isso para que ele sempre, ao submeter o formulario, reinicie o contador de busca

Talvez com isso vocês consigam verificar melhor daí. Obviamente que alterei aqui como teste apenas, aguardamos vocês verificarem.

**Comment by neijobson** [comment]
@ljsts01 
Atualize o módulo para a v4.1.2: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
E use no SEI 4.0.12.

Nos confirma se o problema persiste. Não altere os pontos acima sugeridos.

**Comment by neijobson** [comment]
@ljsts01 
Testando no SEI 4.0.12, a versão 4.1.2 do módulo continua apresentando algum problema?
