### ISSUE TITLE
Opção de não exibir a lista de documentos

### ISSUE THREAD

**Issue by cjmuller** [anatelgovbr/mod-sei-pesquisa#31]
Prezados,

Até a versão 4.0.1 do módulo tínhamos a opção de exibir ou não a lista de documentos em processos públicos e/ou restritos.
Entendo as mudanças que foram feitas a partir dessa versão, mas temos muita dificuldade em fazer com que os usuários classifiquem de forma correta os documentos. Além disso, temos outros sistemas que integram com o nosso SEI e fica ainda mais complexo essa questão.
Dessa forma, pedimos que avaliem a possibilidade de colocar um novo parâmetro na configuração para ativar/desativar a exibição da lista de documentos. Temos conhecimento de outro órgão que também gostaria de ter essa possibilidade de configuração.
Obrigado.

**Comment by neijobson** [comment]
@cjmuller 
Essa mudança foi feita alinhada com a equipe Seges/MGI do PEN.

Todos os pontos listados são afetos a governança adequada sobre o SEI, processo administrativo eletrônico e LAI.
Inclusive por Integrações pode haver a indicação correta de Nível de Acesso, público ou restrito.

Não não os protocolos mesmo se o teor de um documento for restrito é contrário à LAI, que não admite ocultação de sua existência. O que não se pode é acessar o conteúdo, mas saber o protocolo é contrário à LAI e dever de transparência pública.

Ainda, sobre dificuldades, o órgão deve editar norma interna que oriente a regular instrução processual no SEI. Existe na comunidade e consta na Etapa 8 da Jornada de Implementação um modelo de norma interna: https://www.gov.br/gestao/pt-br/assuntos/processo-eletronico-nacional/Jornada-do-PEN/8-InstitucionalizeaadocaodoPEN
- https://docs.google.com/document/d/121q1epq3btGkl1-HeAyx3_oA4SOk_C6uWUa0Bjl04gk/edit?usp=sharing

Os problemas internos devem ter encaminhamentos e solução, sem ferir princípios gerais da Administração Pública, como ocultação de protocolos ou ter sigilo como regra em vez de ser exceção.

Diante de realidades diversas dos órgãos por não terem feito gestão, orientações e normatização adequadas, foi criado a opção na Administração de "Data de Corte Opcional" para demarcar exatamente a partir de quando documentos públicos realmente devem ficar públicos na Pesquisa Pública (exibe o protocolo, mas tem um chavinha azul nele). Utilizem o referido campo para fazer o corte do uso adequado do SEI e seus reflexos na Pesquisa Pública.

**Comment by caduvieira** [comment]
> Não não os protocolos mesmo se o teor de um documento for restrito é contrário à LAI, que não admite ocultação de sua existência. O que não se pode é acessar o conteúdo, mas saber o protocolo é contrário à LAI e dever de transparência pública

Não ficou claro, para mim, como "saber o protocolo é contrário à LAI". Em que casos saber da existência de um protocolo é contrário a LAI?

> Os problemas internos devem ter encaminhamentos e solução, sem ferir princípios gerais da Administração Pública, como ocultação de protocolos ou ter sigilo como regra em vez de ser exceção.

Também fiquei na dúvida: "...ocultação de protocolos ou ter sigilo como regra..."

**Comment by neijobson** [comment]
@caduvieira 
Redação ficou confusa mesmo.

É contrário à LAI a ocultação dos protocolos. Saber que existe protocolo de documento é alinhado à LAI.
Ocultar existência de protocolo é que é contrário à LAI.

Ocultação de todos os protocolos, mesmo de documentos públicos, acaba por estabelecer restrição de acesso como regra, quando pela LAI (art. 3º) deve ser exceção.
