### ISSUE TITLE
Prefixos na numeração de processos não são interpretados

### ISSUE THREAD

**Issue by brunodavik** [anatelgovbr/mod-sei-pesquisa#32]
Apenas formalizando conversa via e-mail com os desenvolvedores conforme problema descoberto em Jundiaí - SP.

Internamente, a pesquisa do SEI consegue encontrar processos via digitação da numeração mesmo sem incluir os prefixos que temos na máscara. Exemplo: ao buscar pelo nome completo PMJ.0044041/2023, 0044041/2023 ou ainda 44041/2023 todos retornam o processo.

Entretanto, o mesmo comportamento não é reproduzido pela pesquisa pública.

**Comment by gabriel9nc** [comment]
Adicionada correção ainda na v4.1.2 para permitir a pesquisa de Nº SEI com letras em sua composição. 

Obs.: A pesquisa é case sensitive, ou seja, letras maiúsculas ou minúsculas alteram o resultado da pesquisa.

**Comment by gabriel9nc** [comment]
Adicionada correção ainda na v4.1.2 para permitir a pesquisa de Nº SEI com letras em sua composição.

Obs.: A pesquisa é case sensitive, ou seja, letras maiúsculas ou minúsculas alteram o resultado da pesquisa.

**Comment by caduvieira** [comment]
Pelo que eu entendi vocês estão republicando várias vezes a mesma versão do 4.1.2. Então é importante os órgãos saberem que há 'várias versões do 4.1.2' e você pode estar usando uma "versão antiga" da versão 4.1.2.
