### ISSUE TITLE
Instrução errada no arquivo MdPesqSolrUtilExterno.php na versão 4.1.2

### ISSUE THREAD

**Issue by diegossalmeida** [anatelgovbr/mod-sei-pesquisa#34]
Na linha 33 do arquivo MdPesqSolrUtilExterno.php há um if ternário com a instrução errada (um : no lugar de ?).
Código atual:
`$arrPalavrasQ[$i] = ($tag == null) : '"' . $arrPalavrasQ[$i] . '"' : $tag . ':"' . $arrPalavrasQ[$i] . '"';`

Sugestão de correção:
`$arrPalavrasQ[$i] = ($tag == null) ? '"' . $arrPalavrasQ[$i] . '"' : $tag . ':"' . $arrPalavrasQ[$i] . '"';`

**Comment by neijobson** [comment]
@diegossalmeida
Tinha erro aí mesmo.
E no final do código.

Corrigimos e republicamos a v4.1.2: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
