### ISSUE TITLE
Problema na visualização de documentos do tipo Formulário

### ISSUE THREAD

**Issue by diegossalmeida** [anatelgovbr/mod-sei-pesquisa#36]
No módulo de Pesquisa Pública, a exibição de documentos do tipo Formulário não está funcionando corretamente.

No SEI, um formulário de exemplo, é exibido da seguinte forma:
![Captura de tela 2024-09-26 114827](https://github.com/user-attachments/assets/91553e4d-8c4f-401f-ac45-84d1dd2d7873)

Já no módulo de pesquisa pública, o mesmo documento é exibido da seguinte forma:
![Captura de tela 2024-09-26 115028](https://github.com/user-attachments/assets/2a6da131-b8dc-4f4a-b64d-798526192bb1)

Além do formato desconfigurado, as informações de assinatura e rodapé do documento não são exibidas.

**Comment by neijobson** [comment]
@diegossalmeida
Publicamos a v4.2.1 com a correção acima na exibição de documentos do tipo Formulário pela Pesquisa Pública: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
