### ISSUE TITLE
filtrar o resultado da pesquisa por data (coluna)

### ISSUE THREAD

**Issue by denysjr** [anatelgovbr/mod-sei-pesquisa#37]
bom dia!

Estou utilizando o SEI 4.0.12.15, com módulo Pesquisa Pública  4.1.2

Vou anexar uma imagem para melhor explicar:

![image](https://github.com/user-attachments/assets/bb5a3e8f-ce1a-44b2-a644-6d4f57fa80cb)

"Gostaria de saber se é possível inverter a ordem da coluna 'Data', de modo que a pesquisa retorne o processo com a data mais recente primeiro."

**Comment by neijobson** [comment]
@denysjr

Não vamos implementar essa evolução, pois o Acesso Externo do core do SEI não tem essa facilidade de ordenação.
Assim, o acesso externo pelo Pesquisa Pública também não.

![image](https://github.com/user-attachments/assets/11a2f367-5000-43bd-b46d-f9a92035ecd2)
