### ISSUE TITLE
Restrição de documentos e processos (externo)

### ISSUE THREAD

**Issue by denysjr** [anatelgovbr/mod-sei-pesquisa#39]
Olá, bom dia!

É possível restringir o acesso público e externo a documentos e processos que foram classificados incorretamente?

![image](https://github.com/user-attachments/assets/003be7d7-f118-441c-9327-2858a7e807be)

**Comment by denysjr** [comment]
esse tópico https://github.com/anatelgovbr/mod-sei-pesquisa/issues/31
responde minha dúvida?

**Comment by neijobson** [comment]
@denysjr
Não é possível, pois não há como saber o que foi classificado correto ou errado.

O órgão deve normatizar e orientar toda a casa a respeito de LAI e níveis de acesso no SEI.

O módulo agora possui o campo de "Data de Corte Opcional" na Administração do módulo para fins de ter uma data de corte antes e depois das questões normativas e orientações internas estarem mais bem definidas no órgão. Para entender o funcionamento do mencionado campo que ajuda em transição do órgão para melhor orientar internamente a instituição, leia ícone de Ajuda sobre o mencionado campo na tela de Administração do módulo.
