### ISSUE TITLE
Adicionar opção "Imprimir" na tela de Pesquisa Processual

### ISSUE THREAD

**Issue by LissFaulhaber** [anatelgovbr/mod-sei-pesquisa#7]
Após alguns testes, percebemos que, aparentemente, a impressão da tela Pesquisa Processual não se adequa bem quando o processo possui uma lista de protocolos e andamentos muito extensa (o que implica numa paginação do PDF a ser gerado na impressão). Com isso, gostaria de sugerir que fosse adicionado um botão "Imprimir" nesta Tela.

**Comment by neijobson** [comment]
Criamos Estória de Usuário internamente para absorver o Pull Request apresentado para essa finalidade

**Comment by neijobson** [comment]
@LissFaulhaber 
Botão "Imprimir" incluído na tela de acesso do processo.
Vide merge: https://github.com/anatelgovbr/mod-sei-pesquisa/pull/14/files

v4.1.1 publicada: https://github.com/anatelgovbr/mod-sei-pesquisa/releases
