### ISSUE TITLE
Erro ao exibir arquivo em acesso externo

### ISSUE THREAD

**Issue by diegossalmeida** [anatelgovbr/mod-sei-pesquisa#8]
Ao tentar exibir arquivo em acesso externo, o módulo está gerando um erro. O problema acontece porque existe um "print_r" no arquivo md_pesq_processo_exibe_arquivo.php, na linha 33.

**Link do arquivo**:
https://github.com/anatelgovbr/mod-sei-pesquisa/blob/d179b2079a7eb2b0d38426fb1860b01c592cccee/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php#L33

**Detalhes do erro:**
Descrição:
Exception: 'Warning: /opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php linha:52.
Cannot
modify header information - headers already sent by (output started at 
/opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php:33)
' in /opt/infra/infra_php/Infra.php:214
Stack trace:
#0 [internal function]: infraGerarExcecao(2, 'Cannot modify h...', '/opt/se...', 52, Array)
#1 /opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php(52): header('Pragma: public')
#2 {main}

Mensagem:
'Warning: /opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php linha:52.
Cannot
modify header information - headers already sent by (output started at 
/opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php:33)
'

Trilha de Processamento:
#0 [internal function]: infraGerarExcecao(2, 'Cannot modify h...', '/opt/se...', 52, Array)
#1 /opt/sei/web/modulos/pesquisa/md_pesq_processo_exibe_arquivo.php(52): header('Pragma: public')
#2 {main}

**Comment by neijobson** [comment]
@diegossalmeida Corrigimos o problema em questão.
Vide o Pull Request a seguir: https://github.com/anatelgovbr/mod-sei-pesquisa/pull/12/files

Republicamos a v4.1.0 com mais correções além dessa indicada e melhoria no CAPTCHA: https://github.com/anatelgovbr/mod-sei-pesquisa/releases

Incrementos na v4.1.0 republicada:

## Correções desta Versão
...
2. Correção para tratamento de exceções no arquivo md_pesq_processo_exibe_arquivo.php, retirando o print_r($versaoSei) na sua linha 33.

## Evoluções desta Versão
...
6. Melhorias no funcionamento do CAPTCHA na tela de pesquisa e na modal do “Gerar PDF” na tela do acesso externo do processo.
	- 6.1. Evolução para incluir o novo componente de CAPTCHA do SEI 4.0 com opção de escutar o CAPTCHA em áudio.
...
