### ISSUE TITLE
Erro ao gerar PDF de documentos do processo

### ISSUE THREAD

**Issue by fsralves** [anatelgovbr/mod-sei-pesquisa#9]
Na linha 33 do arquivo md_pesq_processo_exibe_arquivo.php, o seguinte comando deve ser comentado, pois ocorre erro ao montar o header
//print_r($versaoSei);

**Comment by neijobson** [comment]
@fsralves 
Corrigimos o problema em questão.
Vide o Pull Request a seguir: https://github.com/anatelgovbr/mod-sei-pesquisa/pull/12/files

Republicamos a v4.1.0 com mais correções além dessa indicada e melhoria no CAPTCHA: https://github.com/anatelgovbr/mod-sei-pesquisa/releases

Incrementos na v4.1.0 republicada:

## Correções desta Versão
...
2. Correção para tratamento de exceções no arquivo md_pesq_processo_exibe_arquivo.php, retirando o print_r($versaoSei) na sua linha 33.

## Evoluções desta Versão
...
6. Melhorias no funcionamento do CAPTCHA na tela de pesquisa e na modal do “Gerar PDF” na tela do acesso externo do processo.
	- 6.1. Evolução para incluir o novo componente de CAPTCHA do SEI 4.0 com opção de escutar o CAPTCHA em áudio.
...
